/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zero123_PyMcBridge_ModLoader */

#ifndef _Included_org_zero123_PyMcBridge_ModLoader
#define _Included_org_zero123_PyMcBridge_ModLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    loadServerThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_loadServerThread
  (JNIEnv *, jclass);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    loadClientThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_loadClientThread
  (JNIEnv *, jclass);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    destroyServerThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_destroyServerThread
  (JNIEnv *, jclass);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    destroyClientThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_destroyClientThread
  (JNIEnv *, jclass);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    getPyServerLiveState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zero123_PyMcBridge_ModLoader_getPyServerLiveState
  (JNIEnv *, jclass);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    getPyClientLiveState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zero123_PyMcBridge_ModLoader_getPyClientLiveState
  (JNIEnv *, jclass);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    flushPyStdout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_flushPyStdout
  (JNIEnv *, jclass);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    execPyCode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_execPyCode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    addEnvPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_addEnvPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    setTargetMods
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_setTargetMods
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    setPyForceUseUTF8
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_setPyForceUseUTF8
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    setPythonHome
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_setPythonHome
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zero123_PyMcBridge_ModLoader
 * Method:    setPyLineFlushMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_ModLoader_setPyLineFlushMode
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
