/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zero123_PyMcBridge_EventManager */

#ifndef _Included_org_zero123_PyMcBridge_EventManager
#define _Included_org_zero123_PyMcBridge_EventManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zero123_PyMcBridge_EventManager
 * Method:    callServerEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_EventManager_callServerEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zero123_PyMcBridge_EventManager
 * Method:    callClientEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_EventManager_callClientEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zero123_PyMcBridge_EventManager
 * Method:    callServerJsonEvent
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_EventManager_callServerJsonEvent
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_zero123_PyMcBridge_EventManager
 * Method:    callClientJsonEvent
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zero123_PyMcBridge_EventManager_callClientJsonEvent
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
